// src/components/Header.vue
<script>
export default {
  props: ["isDarkMode", "toggle"],
};
</script>

<template>
  <header class="header">
    <div class="container">
      <div class="flex flex-jc-sb flex-ai-c mb-md">
        <router-link to="/" class="header__brand">edriso</router-link>

        <button
          class="header__toggle"
          @click="toggle"
          aria-label="toggle darkMode"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            stroke-width="2"
          >
            <path
              v-if="isDarkMode"
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
            />

            <path
              v-else
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
            />
          </svg>
        </button>
      </div>

      <nav class="header__nav flex flex-jc-c flex-gap-lg">
        <router-link :to="{ name: 'about' }">About</router-link>
        <router-link :to="{ name: 'showcase' }">Showcase</router-link>
        <router-link :to="{ name: 'kudos' }">Kudos</router-link>
        <router-link :to="{ name: 'contact' }">Contact</router-link>
      </nav>
    </div>
  </header>
</template>

// src/components/Header.jsx
import { NavLink, Link } from 'react-router-dom';
import { useEffect, useState } from 'react';

function Header() {
  const [isDark, setIsDark] = useState(() => {
    const saved = localStorage.getItem('darkMode');
    if (saved !== null) return saved === 'true';
    return window.matchMedia('(prefers-color-scheme: dark)').matches;
  });

  useEffect(() => {
    document.documentElement.classList.toggle('dark', isDark);
    localStorage.setItem('darkMode', isDark);
  }, [isDark]);

  const navLinks = [
    { to: '/', label: 'About' },
    { to: '/showcase', label: 'Showcase' },
    { to: '/kudos', label: 'Kudos' },
    { to: '/contact', label: 'Contact' },
  ];

  return (
    <header className="sticky top-0 z-50 bg-(--color-bg-header) border-b border-(--color-border) transition-colors duration-300">
      <div className="mx-auto max-w-[1110px] px-5 py-4 md:px-8">
        <div className="flex items-center justify-between mb-3">
          <Link to="/" className="font-display text-2xl hover:no-underline">
            edriso
          </Link>

          <button
            onClick={() => setIsDark(!isDark)}
            className="p-2 rounded-lg hover:bg-(--color-bg) transition-colors cursor-pointer"
            aria-label="Toggle dark mode"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
              className="w-5 h-5"
            >
              {isDark ? (
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
                />
              ) : (
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
                />
              )}
            </svg>
          </button>
        </div>

        <nav className="flex justify-center gap-6">
          {navLinks.map((link) => (
            <NavLink
              key={link.to}
              to={link.to}
              end={link.to === '/'}
              className={({ isActive }) =>
                `text-sm font-medium pb-1 border-b-2 transition-colors ${
                  isActive
                    ? 'border-(--color-active) text-(--color-active)'
                    : 'border-transparent hover:text-(--color-active)'
                }`
              }
            >
              {link.label}
            </NavLink>
          ))}
        </nav>
      </div>
    </header>
  );
}

export default Header;
